
service: matcha-lambda
# app and org for use with dashboard.serverless.com
app: matchakon
org: haubar
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x

  
functions:
  hello:
    handler: handler.hello
  
  createMatcha:
    handler: handler.createMatcha
    events:
      - http:
          path: matcha
          method: post
          cors: true

  updateMatcha:
    handler: handler.updateMatcha
    events:
      - http:
          path: matcha/{id}
          method: put
          cors: true

  deleteMatcha:
    handler: handler.deleteMatcha
    events:
      - http:
          path: matcha/{id}
          method: delete
          cors: true

  matcha:
    handler: handler.matcha
    events:
      - http:
          path: matcha/{id}
          method: get
          cors: true