
service: matcha-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name


provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
  
  createMatcha:
    handler: handler.createMatcha
    events:
      - http:
          path: user
          method: post
          cors: true

  updateMatcha:
    handler: handler.updateMatcha
    events:
      - http:
          path: matcha/{id}
          method: put
          cors: true

  deleteMatcha:
    handler: handler.deleteMatcha
    events:
      - http:
          path: matcha/{id}
          method: delete
          cors: true

  matcha:
    handler: handler.matcha
    events:
      - http:
          path: matcha/{id}
          method: get
          cors: true